[versions]
about-libraries = "10.10.0"
material = "1.5.11"

[libraries]
material-icons = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "material" }
material3 = { module = "org.jetbrains.compose.material3:material3-desktop", version.ref = "material" }
about-libraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "about-libraries" }
about-libraries-compose = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "about-libraries" }

[plugins]
about-libraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "about-libraries" }